services:
  web:
    build: .
    container_name: web-achifoni-rec
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: db-achifoni-rec
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recuperacio_php
      MYSQL_USER: recupera
      MYSQL_PASSWORD: recupera123
    volumes:
      - ./db-recuperacio:/var/lib/mysql
    ports:
      - "3309:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-achifoni-rec
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: recupera
      PMA_PASSWORD: recupera123
    ports:
      - "8084:80"
